### ISSUE TITLE
Help with Universe

### ISSUE THREAD

**Issue by busheezy** [DoctorMcKay/node-steamid#2]
Is there an efficient way to figure out what universe a 64 bit id will have in a steam2 game? I see you have the boolean for newer format in getSteam2RenderedID but I feel like I'm missing a piece of the puzzle.

I see steamid.io is representing the first digit correctly and I'm wondering if there is a method to the madness. Do you know if it perhaps is associated with the date the profile was created?

I see it your post here: 
https://dev.doctormckay.com/topic/433-whats-in-a-steamid/
That you refer to it by the age of the game. I'm not sure what that means. I thought you could create a steam account without having a game but I guess I'm not sure.

I copy and pasted your library to make a quick piece of test code to get the universe just to see and I guess everything is returned as 1.

```js
const UInt64 = require('cuint').UINT64;

const id = '76561197972581267';
const id2 = '76561198138240610';

const numUInt = new UInt64(id, 10);
const numUInt2 = new UInt64(id2, 10);

function outputTest(num) {
  const accountid = (num.toNumber() & 0xFFFFFFFF) >>> 0;
  const instance = num.shiftRight(32).toNumber() & 0xFFFFF;
  const type = num.shiftRight(20).toNumber() & 0xF;
  const universe = num.shiftRight(4).toNumber();

  console.log(universe);
}

outputTest(numUInt);
outputTest(numUInt2);
```

As I'm guessing you know, this outputs:
```
1
1
```

I was wanting to use AdminId.BindIdentity in sourcemod and I think it only accepts steam2 but I might be wrong.

Any guidance is appreciated.

**Comment by DoctorMcKay** [comment]
Every account's universe is always 1. Older Source games show STEAM_0:X:Y instead of STEAM_1:X:Y but the universe is always 1 regardless.

For Steam2 IDs, SourceMod only stores from the 8th character onwards (0-indexed), so STEAM_0:0:23071901 and STEAM_1:0:23071901 both get stored and compared internally as `0:23071901` so both will work.

**Comment by busheezy** [comment]
Thank you for all of the info. I very much appreciate it.
